services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Component\HttpClient\MockHttpClient: ~

    Symfony\Contracts\HttpClient\HttpClientInterface: '@Symfony\Component\HttpClient\MockHttpClient'
